export interface MenuItem {
  id: string;
  nameEn: string;
  nameAr: string;
  descEn?: string;
  descAr?: string;
  price: string;
  isPopular?: boolean;
}

export const menuData: Record<string, MenuItem[]> = {
  breakfast: [
    { id: "b1", nameEn: "Al Rewaq Breakfast Offer (4 Persons)", nameAr: "عرض فطور الرواق (4 اشخاص)", descEn: "Includes tax and service charge", descAr: "شامل الضريبة والخدمة", price: "20.00", isPopular: true },
    { id: "b2", nameEn: "Al Rewaq Breakfast Offer (2 Persons)", nameAr: "عرض فطور الرواق لشخصين", descEn: "Includes tax and service charge", descAr: "شامل الضريبة والخدمة", price: "15.00" },
    { id: "b3", nameEn: "Omelette Disc", nameAr: "قرص عجة", price: "2.50" },
    { id: "b4", nameEn: "Service Plate", nameAr: "صحن سيرفس", price: "2.00" },
    { id: "b5", nameEn: "Sambousek 4 Pcs (Cheese)", nameAr: "سمبوسك 4 حبات (جبنة)", price: "2.50" },
    { id: "b6", nameEn: "Fries & Cheese Plate", nameAr: "صحن بطاطا و جبنة", price: "3.00" },
    { id: "b7", nameEn: "French Fries Plate", nameAr: "صحن بطاطا", price: "2.50" },
    { id: "b8", nameEn: "Fried Kibbeh (4 Pcs)", nameAr: "كبة مقلية (٤ حبات )", price: "2.15" },
    { id: "b9", nameEn: "Fattet Hummus", nameAr: "فتة حمص", price: "3.50" },
    { id: "b10", nameEn: "Sausages with Vegetables", nameAr: "نقانق بالخضار", price: "3.00" },
    { id: "b11", nameEn: "Hash Brown (3 Pcs)", nameAr: "هاش براون (3 حبات)", price: "3.50" },
    { id: "b12", nameEn: "Potato Mfarakeh", nameAr: "مفركة بطاطا", price: "2.50" },
    { id: "b13", nameEn: "Tomato Fry with Meat & Nuts", nameAr: "قلاية بندورة باللحمة والمكسرات", descEn: "Net meat weight 250g", descAr: "وزن اللحمة الصافي (250غ)", price: "5.50", isPopular: true },
    { id: "b14", nameEn: "Fried Halloumi", nameAr: "حلوم مقلي", price: "2.50" },
    { id: "b15", nameEn: "Tomato Fry", nameAr: "قلاية بندورة", price: "2.60" },
    { id: "b16", nameEn: "Pickles", nameAr: "مخلل", price: "1.00" },
    { id: "b17", nameEn: "Olives (Black / Green)", nameAr: "زيتون (أسود / أخضر)", price: "0.80" },
    { id: "b18", nameEn: "Makdous", nameAr: "مقدوس", price: "1.50" },
    { id: "b19", nameEn: "Feta Cheese", nameAr: "جبنة فيتا", price: "1.00" },
    { id: "b20", nameEn: "Yellow Cheese", nameAr: "جبنة صفراء", price: "1.00" },
    { id: "b21", nameEn: "Butter & Jam (Apricot / Strawberry)", nameAr: "زبدة ومربى (مشمش / فراولة )", price: "1.00" },
    { id: "b22", nameEn: "Turkey (Small)", nameAr: "تيركي (صغير )", price: "1.50" },
    { id: "b23", nameEn: "Baba Ghanouj", nameAr: "بابا غنوج", price: "2.25" },
    { id: "b24", nameEn: "Mutabbal Eggplant", nameAr: "متبل باذنجان", price: "2.00" },
    { id: "b25", nameEn: "Hummus with Meat & Nuts", nameAr: "حمص باللحمة والمكسرات", descEn: "Net meat weight 200g", descAr: "وزن اللحمة الصافي (200غ)", price: "5.00" },
    { id: "b26", nameEn: "Beiruti Hummus", nameAr: "حمص بيروتي", price: "2.50" },
    { id: "b27", nameEn: "Eggs & Sausage Pottery", nameAr: "فخارة بيض و نقانق", price: "2.25" },
    { id: "b28", nameEn: "Eggs & Cheese Pottery", nameAr: "فخارة بيض و جبنة", price: "2.00" },
    { id: "b29", nameEn: "Eggs Pottery", nameAr: "فخارة بيض", price: "1.50" },
    { id: "b30", nameEn: "Foul Plate", nameAr: "صحن فول", price: "1.70" },
    { id: "b31", nameEn: "Falafel Plate", nameAr: "صحن فلافل", price: "1.25" },
    { id: "b32", nameEn: "Eggs with Tomato Pottery", nameAr: "فخارة بيض بالبندورة", price: "2.25" },
    { id: "b33", nameEn: "Hummus Plate", nameAr: "صحن حمص", price: "2.00" },
    { id: "b34", nameEn: "White Cheese", nameAr: "جبنة بيضاء", price: "2.75" },
    { id: "b35", nameEn: "Mozzarella Sticks", nameAr: "موزريلا ستيك", price: "3.00" },
    { id: "b36", nameEn: "Shanklish", nameAr: "شنقليش", price: "3.25" }
  ],
  coldAppetizers: [
    { id: "c1", nameEn: "Talet Al Qodus Salad", nameAr: "سلطة طلة القدس", price: "6.00", isPopular: true },
    { id: "c2", nameEn: "Pineapple Tabbouleh", nameAr: "تبولة الأنناس", price: "3.75" },
    { id: "c3", nameEn: "Tabbouleh", nameAr: "تبولة", price: "3.50" },
    { id: "c4", nameEn: "Yalanji (Stuffed Grape Leaves)", nameAr: "يلنجي", price: "3.50" },
    { id: "c5", nameEn: "Caesar Salad", nameAr: "سلطة سيزر", price: "3.25" },
    { id: "c6", nameEn: "Caesar with Chicken", nameAr: "سيزر مع دجاج", price: "4.00" },
    { id: "c7", nameEn: "Farmer's Salad (Fallahia)", nameAr: "سلطة فلاحية", price: "2.70" },
    { id: "c8", nameEn: "Parsley Salad (Bagdounsia)", nameAr: "بقدونسية", price: "2.70" },
    { id: "c9", nameEn: "Cucumber with Yogurt", nameAr: "خيار باللبن", price: "2.00" },
    { id: "c10", nameEn: "Turkish Salad", nameAr: "سلطة تركية", price: "2.25" },
    { id: "c11", nameEn: "Mixed Appetizers Plate", nameAr: "صحن مقبلات مكس", descEn: "Muhammara, Spicy Labneh with Walnuts, Turkish Salad, Beetroot Mutabbal", descAr: "(محمرة ، لبنة حارة بالجوز ، سلطة تركية ، متبل شمندر )", price: "4.00", isPopular: true },
    { id: "c12", nameEn: "Arugula (Rocca) Salad", nameAr: "سلطة جرجير", price: "2.90" },
    { id: "c13", nameEn: "Greek Salad", nameAr: "سلطة يونانية", price: "3.25" },
    { id: "c14", nameEn: "Fattoush Salad", nameAr: "سلطة فتوش", price: "2.90" },
    { id: "c15", nameEn: "Corn Salad", nameAr: "سلطة ذرة", price: "2.50" },
    { id: "c16", nameEn: "Coleslaw Salad", nameAr: "سلطة كولسلو", price: "2.25" },
    { id: "c17", nameEn: "Mutabbal Eggplant", nameAr: "متبل باذنجان", price: "2.25" },
    { id: "c18", nameEn: "Hummus Plate", nameAr: "صحن حمص", price: "2.25" },
    { id: "c19", nameEn: "Baba Ghanouj Plate", nameAr: "صحن بابا غنوج", price: "2.25" },
    { id: "c20", nameEn: "Yogurt Plate", nameAr: "صحن لبن رايب", price: "1.50" },
    { id: "c21", nameEn: "Arabic Salad", nameAr: "سلطة عربية", price: "2.40" },
    { id: "c22", nameEn: "Beetroot Mutabbal", nameAr: "متبل شمندر", price: "2.50" },
    { id: "c23", nameEn: "Muhammara Plate", nameAr: "صحن محمرة", price: "2.50" },
    { id: "c24", nameEn: "Spicy Labneh with Walnuts", nameAr: "لبنة حارة بالجوز", price: "2.50" },
    { id: "c25", nameEn: "Healthy Talet Al Qodus Salad", nameAr: "سلطة طلة القدس الصحية", price: "6.00" },
    { id: "c26", nameEn: "Pomelo Salad", nameAr: "سلطة بوملي", price: "6.00" },
    { id: "c27", nameEn: "Beiruti Hummus", nameAr: "حمص بيروتي", price: "2.75" },
    { id: "c28", nameEn: "Feta Cheese", nameAr: "جبنة فيتا", price: "2.00" }
  ],
  hotAppetizers: [
    { id: "ha1", nameEn: "Grilled Halloumi", nameAr: "حلوم جرل", price: "2.90" },
    { id: "ha2", nameEn: "Hash Browns", nameAr: "هاش براون", price: "3.50" },
    { id: "ha3", nameEn: "Feta", nameAr: "فيتا", price: "2.00" },
    { id: "ha4", nameEn: "Borek & Kibbeh Plate", nameAr: "صحن برك و كبة", price: "2.50", isPopular: true },
    { id: "ha5", nameEn: "Spicy Potato (Batata Harra)", nameAr: "بطاطا حارة", price: "3.00" },
    { id: "ha6", nameEn: "Nachos", nameAr: "ناتشوز", price: "6.00" },
    { id: "ha7", nameEn: "Fried Kibbeh (4 Pcs)", nameAr: "كبة مقلية ٤ حبات", price: "3.25" },
    { id: "ha8", nameEn: "Tomato Fry with Meat & Nuts", nameAr: "قلاية بندورة باللحمة والمكسرات", price: "5.50" },
    { id: "ha9", nameEn: "Hummus with Meat & Nuts", nameAr: "حمص باللحمة والمكسرات", price: "5.00" },
    { id: "ha10", nameEn: "Fries with Cheese Plate", nameAr: "صحن بطاطا بالجبنة", price: "3.00" },
    { id: "ha11", nameEn: "French Fries Plate", nameAr: "صحن بطاطا", price: "2.50" },
    { id: "ha12", nameEn: "Sambousek 4 Pcs (Cheese)", nameAr: "سمبوسك 4 حبات - جبنه", price: "2.50" }
  ],
  grills: [
    { id: "g1", nameEn: "Mixed Grill (1 Kg)", nameAr: "مشكل 1كيلو", price: "25.00", isPopular: true },
    { id: "g2", nameEn: "Mixed Grill (1/2 Kg)", nameAr: "مشكل نصف كيلو", price: "13.50" },
    { id: "g3", nameEn: "Shish Kebab / Shaff (1 Kg)", nameAr: "شقف 1كيلو", price: "26.00" },
    { id: "g4", nameEn: "Shish Kebab / Shaff (1/2 Kg)", nameAr: "شقف نصف كيلو", price: "14.00" },
    { id: "g5", nameEn: "Kebab (1 Kg)", nameAr: "كباب 1 كيلو", price: "21.00" },
    { id: "g6", nameEn: "Kebab (1/2 Kg)", nameAr: "كباب نصف كيلو", price: "11.00" },
    { id: "g7", nameEn: "Shish Tawook (1 Kg)", nameAr: "شيش طاووق 1 كيلو", price: "18.00" },
    { id: "g8", nameEn: "Shish Tawook (1/2 Kg)", nameAr: "شيش طاووق نصف كيلو", price: "9.00" }
  ],
  mains: [
    { id: "m1", nameEn: "Meat Sajia (1/2 Kg)", nameAr: "صاجية لحمة (1/2)", descEn: "Price per Kg: 18.00 JD", descAr: "الكيلو 18.00 JD", price: "9.00", isPopular: true },
    { id: "m2", nameEn: "Kids Meal", nameAr: "وجبة اطفال", descEn: "Tenders, Nuggets", descAr: "(تندر، ناقيت)", price: "3.75" },
    { id: "m3", nameEn: "Chicken Pottery", nameAr: "فخارة جاج", price: "6.75" },
    { id: "m4", nameEn: "Creamy Chicken Pottery", nameAr: "فخارة دجاج بالكريمة", price: "7.50", isPopular: true },
    { id: "m5", nameEn: "Eggplant Manzalah Tray", nameAr: "صينية منزلة بيذنجان", price: "6.50" },
    { id: "m6", nameEn: "Cauliflower & Meat Tray", nameAr: "صينية زهرة و لحمة", price: "6.50" },
    { id: "m7", nameEn: "Kofta Tray with Tomato (500g)", nameAr: "صينية كفتة بالبندورة 500غ", price: "6.50" },
    { id: "m8", nameEn: "Kofta Tray with Tahini (500g)", nameAr: "صينية كفتة بالطحينية 500غ", price: "6.50" },
    { id: "m9", nameEn: "Ras Asfour (Meat) with Veggies Pottery", nameAr: "فخارة راس عصفور مع الخضار", price: "7.50" },
    { id: "m10", nameEn: "Zinger Pottery", nameAr: "فحارة زنجر", price: "6.00" },
    { id: "m11", nameEn: "Fusilli White Sauce", nameAr: "فوسيلي وايت صوص", price: "3.50" },
    { id: "m12", nameEn: "Spaghetti Bolognese", nameAr: "إسباجيتي بلونيز", descEn: "Meat & Tomato Sauce", descAr: "(لحمة&صوص البندورة)", price: "4.75" },
    { id: "m13", nameEn: "Fettuccine with Chicken", nameAr: "فوتوتشيني مع دجاج", price: "3.90" },
    { id: "m14", nameEn: "Meat Lasagna", nameAr: "لازانيا باللحمة", price: "5.00" },
    { id: "m15", nameEn: "Penne Arrabiata (Rosé Sauce)", nameAr: "بنا اربياتا (صوص روزية)", price: "3.50" }
  ],
  coldDrinks: [
    { id: "cd1", nameEn: "Pepsi", nameAr: "بيبسي", descEn: "Diet Available", descAr: "يوجد دايت", price: "1.25" },
    { id: "cd2", nameEn: "Mirinda", nameAr: "ميرندا", price: "1.25" },
    { id: "cd3", nameEn: "7 Up", nameAr: "سفن اب", descEn: "Diet Available", descAr: "يوجد دايت", price: "1.25" },
    { id: "cd4", nameEn: "Red Bull", nameAr: "ريد بول", descEn: "Choose Flavor (+0.5)", descAr: "( +0.5 اختار النكهة )", price: "2.90" },
    { id: "cd5", nameEn: "Sparkling Water", nameAr: "مياه غازيه", price: "1.25" },
    { id: "cd6", nameEn: "Caramel Frappe", nameAr: "فرابيه كرمل", price: "3.00" },
    { id: "cd7", nameEn: "Mocha Frappe", nameAr: "موكا فرابيه", price: "3.00" },
    { id: "cd8", nameEn: "Vanilla Frappe", nameAr: "فرابيه ڤنيلا", price: "3.00" },
    { id: "cd9", nameEn: "Ice Mocha", nameAr: "آيس موكا", price: "3.00" },
    { id: "cd10", nameEn: "Ice White Mocha", nameAr: "آيس وايت موكا", price: "3.00" },
    { id: "cd11", nameEn: "Ice Caramel Macchiato", nameAr: "آيس كراميل ميكاتو", price: "3.00" },
    { id: "cd12", nameEn: "Ice Tea", nameAr: "آيس تي", descEn: "Peach / Lemon / Passion Fruit", descAr: "خوخ / ليمون / باشن فروت", price: "2.50" },
    { id: "cd13", nameEn: "Classic Mojito", nameAr: "موهيتو كلاسك", price: "2.50" },
    { id: "cd14", nameEn: "Strawberry Mojito", nameAr: "موهيتو فراولة", price: "3.00", isPopular: true },
    { id: "cd15", nameEn: "Passion Fruit Mojito", nameAr: "موهيتو باشن فروت", price: "3.00" },
    { id: "cd16", nameEn: "Rose Mojito", nameAr: "موهيتو ورد", price: "3.00" },
    { id: "cd17", nameEn: "Raspberry Mojito", nameAr: "موهيتو راز بيري", price: "3.00" },
    { id: "cd18", nameEn: "Energy Mix", nameAr: "مكس الطاقة", price: "3.75" },
    { id: "cd19", nameEn: "Blue Ocean Mix", nameAr: "مكس بلو اوشن", price: "3.50" },
    { id: "cd20", nameEn: "Lotus Frappe", nameAr: "فرابية لوتس", price: "3.25" },
    { id: "cd21", nameEn: "Oreo Frappe", nameAr: "فرابية اوريو", price: "3.25" },
    { id: "cd22", nameEn: "Ice Red Velvet Latte", nameAr: "ايس ريد ڤيلڤت لاتية", price: "3.50" },
    { id: "cd23", nameEn: "Blue Curacao Mojito", nameAr: "موهيتو بلوكرا ساو", price: "3.00" },
    { id: "cd24", nameEn: "Bubblegum Mojito", nameAr: "موهيتو ببلجم", price: "3.00" },
    { id: "cd25", nameEn: "Mixed Berry Mojito", nameAr: "موهيتو مكس بيري", price: "3.00" },
    { id: "cd26", nameEn: "Apple Mojito", nameAr: "موهيتو تفاح", price: "3.00" },
    { id: "cd27", nameEn: "Watermelon Mojito", nameAr: "موهيتو بطيخ", price: "3.00" },
    { id: "cd28", nameEn: "Ice Spanish Latte", nameAr: "ايس سبانش لاتيه", price: "2.50" },
    { id: "cd29", nameEn: "Shanineh (Yogurt Drink)", nameAr: "شنينة", price: "1.50" },
    { id: "cd30", nameEn: "Ice Latte", nameAr: "آيس لاتيه", descEn: "Choose Flavor", descAr: "( اختار النكهة )", price: "3.00" },
    { id: "cd31", nameEn: "Orange Juice", nameAr: "برتقال", price: "2.50" },
    { id: "cd32", nameEn: "Lemon Juice", nameAr: "ليمون", price: "2.50" },
    { id: "cd33", nameEn: "Lemon & Mint Juice", nameAr: "ليمون ونعنع", price: "2.90", isPopular: true },
    { id: "cd34", nameEn: "Kiwi Juice", nameAr: "كيوي", price: "3.25" },
    { id: "cd35", nameEn: "Strawberry Juice", nameAr: "فراولة", price: "2.90" },
    { id: "cd36", nameEn: "Mango Juice", nameAr: "مانجا", price: "3.50" },
    { id: "cd37", nameEn: "Pineapple Juice", nameAr: "أناناس", price: "3.25" },
    { id: "cd38", nameEn: "Pomegranate Juice", nameAr: "رمان", descEn: "100% Natural", descAr: "ولله طبيعي", price: "3.50", isPopular: true },
    { id: "cd39", nameEn: "Kiwi & Strawberry", nameAr: "كيوي و فرولة", price: "3.25" },
    { id: "cd40", nameEn: "Strawberry & Mango", nameAr: "فرولة و منجا", price: "3.25" },
    { id: "cd41", nameEn: "Kiwi & Lemon", nameAr: "كيوي و ليمون", price: "3.25" },
    { id: "cd42", nameEn: "Mixed Fruit Juice", nameAr: "مكس فروت", price: "3.75" },
    { id: "cd43", nameEn: "Tango Cocktail", nameAr: "تانجو كوكتيل", price: "3.25" },
    { id: "cd44", nameEn: "Tallet Special Cocktail", nameAr: "سبشل الطلة", price: "4.00" },
    { id: "cd45", nameEn: "Banana & Milk", nameAr: "موز وحليب", price: "2.75" },
    { id: "cd46", nameEn: "Avocado Cocktail", nameAr: "أفوكادو", price: "3.75" },
    { id: "cd47", nameEn: "Pina Colada", nameAr: "بيناكولادا", price: "3.25" },
    { id: "cd48", nameEn: "Creamy Passion Fruit", nameAr: "باشن فروت كريمي", price: "3.50" },
    { id: "cd49", nameEn: "Banana, Strawberry & Milk", nameAr: "موز و فراولة و حليب", price: "2.90" },
    { id: "cd50", nameEn: "Strawberry Smoothie", nameAr: "سموذي فرولة", price: "3.00" },
    { id: "cd51", nameEn: "Blueberry Smoothie", nameAr: "سموذي بلوبري", price: "3.00" },
    { id: "cd52", nameEn: "Mixed Berry Smoothie", nameAr: "سموذي مكس بيري", price: "3.00" },
    { id: "cd53", nameEn: "Mango Coconut Smoothie", nameAr: "سموذي مانجو كوكو نت", price: "3.00" },
    { id: "cd54", nameEn: "Raspberry Smoothie", nameAr: "سموذي راز بيري", price: "3.00" },
    { id: "cd55", nameEn: "Kiwi Smoothie", nameAr: "سموذي كيوي", price: "3.00" },
    { id: "cd56", nameEn: "Passion Mango Smoothie", nameAr: "سموذي باشن مانجو", price: "3.00" },
    { id: "cd57", nameEn: "Mango Smoothie", nameAr: "سموذي مانجو", price: "3.00" },
    { id: "cd58", nameEn: "Passion Smoothie", nameAr: "سموذي باشن", price: "3.00" },
    { id: "cd59", nameEn: "Peach Smoothie", nameAr: "سموذي خوخ", price: "3.00" },
    { id: "cd60", nameEn: "Talet Al Qodus Milkshake", nameAr: "ملك شيك طلة القدس", descEn: "Red Velvet (Outstanding!)", descAr: "ريد ڤيلڤت (اشي من الاخر )", price: "4.50", isPopular: true },
    { id: "cd61", nameEn: "Regular Milkshake", nameAr: "ملك شيك نورمل", descEn: "Vanilla / Chocolate / Strawberry", descAr: "( ڤنيلا / شوكلت / فرولة )", price: "2.90" },
    { id: "cd62", nameEn: "Special Milkshake", nameAr: "ملك شيك سبشل", descEn: "Oreo / Snickers / Lotus / Croquant / Arabic / Cheesecake", descAr: "( اوريو / سنكرز / لوتس / كروكان / عربية / تشيز كيك )", price: "3.25" }
  ],
  hotDrinks: [
    { id: "hd1", nameEn: "Turkish Coffee Single", nameAr: "قهوة تركية سنجل", price: "1.75" },
    { id: "hd2", nameEn: "Turkish Coffee Double", nameAr: "قهوة تركية دبل", price: "2.50" },
    { id: "hd3", nameEn: "Espresso Shot", nameAr: "اسبريسو شوت", price: "1.75" },
    { id: "hd4", nameEn: "Espresso Double Shot", nameAr: "اسبريسو دبل شوت", price: "2.50" },
    { id: "hd5", nameEn: "Americano Coffee", nameAr: "اميريكانو كوفي", price: "2.50" },
    { id: "hd6", nameEn: "Macchiato", nameAr: "ميكاياتو", price: "3.00" },
    { id: "hd7", nameEn: "Cappuccino", nameAr: "كابتشينو", descEn: "Add Flavor (+0.5)", descAr: "( +0.5 اختار النكهة )", price: "2.50" },
    { id: "hd8", nameEn: "Latte", nameAr: "لاتيه", descEn: "Add Flavor (+0.5)", descAr: "( +0.5 اختار النكهة )", price: "2.50" },
    { id: "hd9", nameEn: "Caramel Macchiato", nameAr: "كراميل ميكاتو", price: "2.95" },
    { id: "hd10", nameEn: "French Coffee", nameAr: "قهوة فرنسية", price: "2.95" },
    { id: "hd11", nameEn: "Spanish Latte", nameAr: "سبانيش لاتيه", price: "2.75" },
    { id: "hd12", nameEn: "Coffee Mocha", nameAr: "كوفي موكا", price: "2.90" },
    { id: "hd13", nameEn: "White Mocha", nameAr: "وايت موكا", price: "2.75" },
    { id: "hd14", nameEn: "Talet Al Qodus Hot Chocolate", nameAr: "هوت شوكليت طلة القدس", descEn: "With Marshmallows", descAr: "مع مارشملو", price: "3.50", isPopular: true },
    { id: "hd15", nameEn: "Hot Chocolate", nameAr: "هوت شوكليت", descEn: "Add Flavor (+0.5)", descAr: "(اضافة نكهة +0.5)", price: "2.75" },
    { id: "hd16", nameEn: "Nescafe", nameAr: "نسكافيه", price: "2.50" },
    { id: "hd17", nameEn: "Tea", nameAr: "شاي", price: "1.25" },
    { id: "hd18", nameEn: "Karak Tea", nameAr: "شاي كرك", price: "2.00" },
    { id: "hd19", nameEn: "Tallet's Panadol", nameAr: "بندول الطلة", descEn: "Healing is from God, but we try", descAr: "( الشافي الله بس احنا بنحاول )", price: "2.50" },
    { id: "hd20", nameEn: "Herbal Tea (Zohorat)", nameAr: "زهورات", price: "1.25" },
    { id: "hd21", nameEn: "Talet Al Qodus Sahlab", nameAr: "سحلب طلة القدس", descEn: "If not outstanding, return it", descAr: "( اذا مش خطير يرجع )", price: "2.50", isPopular: true },
    { id: "hd22", nameEn: "V60 Coffee", nameAr: "V 60", price: "4.00" },
    { id: "hd23", nameEn: "Cortado", nameAr: "كورتادو", price: "2.50" },
    { id: "hd24", nameEn: "French Press", nameAr: "فرنش بريس", price: "3.50" },
    { id: "hd25", nameEn: "Flat White", nameAr: "فلات وايت", price: "2.25" },
    { id: "hd26", nameEn: "Americano", nameAr: "امريكان", price: "2.50" },
    { id: "hd27", nameEn: "Ginger with Milk", nameAr: "زنجبيل بالحليب", price: "2.00" },
    { id: "hd28", nameEn: "Chamomile", nameAr: "بابونج", price: "1.25" },
    { id: "hd29", nameEn: "Teapot", nameAr: "ابريق شاي", price: "2.75" },
    { id: "hd30", nameEn: "Anise", nameAr: "يانسون", price: "1.25" }
  ],
  desserts: [
    { id: "d1", nameEn: "Um Ali Pottery (4 Persons)", nameAr: "فخارة أم علي (4أشخاص)", price: "6.00", isPopular: true },
    { id: "d2", nameEn: "Um Ali Pottery (2 Persons)", nameAr: "فخارة ام علي (شخصين)", price: "3.00" },
    { id: "d3", nameEn: "Classic Crepe", nameAr: "كريب كلاستك", descEn: "Add Fruit: +0.75 / Add Ice Cream: +0.75", descAr: "اضافة فواكة (فرولة +كيوي +موز) : 0.75 / اضافة سكوب ايس كريم : 0.75", price: "3.50" },
    { id: "d4", nameEn: "Waffle", nameAr: "وافل", descEn: "Add Fruit: +0.75 / Add Ice Cream: +0.75", descAr: "اضافة فواكة (فرولة +كيوي +موز) : 0.75 / اضافة سكوب ايس كريم : 0.75", price: "3.50" },
    { id: "d5", nameEn: "Kunafa", nameAr: "كنافة", descEn: "Soft / Rough", descAr: "(ناعمة / خشنة)", price: "2.00" },
    { id: "d6", nameEn: "Lazy Cake", nameAr: "ليزي كيك", price: "3.00" },
    { id: "d7", nameEn: "Blueberry Cheesecake", nameAr: "تشيز كيك بلوبري", price: "3.50" },
    { id: "d8", nameEn: "Lotus Cheesecake", nameAr: "تشيز كيك لوتس", price: "3.50" },
    { id: "d9", nameEn: "San Sebastian Cheesecake", nameAr: "سان سبستينان", descEn: "Tastier than mom's sweets!", descAr: "ازكى من حلو امي", price: "3.50", isPopular: true },
    { id: "d10", nameEn: "Pistachio Cheesecake", nameAr: "تشيز كيك بيستاشيو", price: "3.50" },
    { id: "d11", nameEn: "Salti Sha'abaniyat", nameAr: "شعبانيات سلطية", price: "2.60" },
    { id: "d12", nameEn: "Qatayef", nameAr: "قطايف", price: "1.75" },
    { id: "d13", nameEn: "Talet Al Qodus Cake", nameAr: "كيكة طلة القدس", price: "3.00" },
    { id: "d14", nameEn: "Kunafa with Pistachios", nameAr: "كنافة بالفستق الحلبي", price: "4.00" },
    { id: "d15", nameEn: "Kunafa with Walnuts", nameAr: "كنافة بالجوز", price: "3.75" },
    { id: "d16", nameEn: "Salti Haituliyah", nameAr: "هيطيلة سلطية", price: "1.60" },
    { id: "d17", nameEn: "Special Ice Cream", nameAr: "إيس كريم سبشل", descEn: "Oreo / Croquant / Cheesecake / Arabic / Lotus / Snickers", descAr: "( أوريو / كروكان / تشيز كيك / عربية / لوتس / سنكرز )", price: "2.25" },
    { id: "d18", nameEn: "Regular Ice Cream", nameAr: "ايس كريم نورمل", descEn: "Strawberry / Vanilla / Chocolate", descAr: "( فرولة / ڤنيلا / شوكلت )", price: "2.00" },
    { id: "d19", nameEn: "Tutti Frutti", nameAr: "توتي فروتي", price: "3.00" }
  ],
  shisha: [
    { id: "s1", nameEn: "Two Apples Fakher", nameAr: "تفاحتين فاخر", price: "4.75", isPopular: true },
    { id: "s2", nameEn: "Two Apples Nakhla", nameAr: "تفاحتين نخلة", price: "4.75" },
    { id: "s3", nameEn: "Two Apples Mazaya", nameAr: "تفاحتين مزايا", price: "4.00" },
    { id: "s4", nameEn: "Lemon & Mint", nameAr: "ليمون ونعنع", price: "4.00" },
    { id: "s5", nameEn: "Watermelon & Mint", nameAr: "بطيخ ونعنع", price: "4.00" },
    { id: "s6", nameEn: "Grapes & Berry", nameAr: "عنب وتوت", price: "4.00" },
    { id: "s7", nameEn: "Gum & Cinnamon", nameAr: "علكة وقرفة", price: "4.00" },
    { id: "s8", nameEn: "Candy & Drops", nameAr: "كاندي ودربس", price: "4.00" },
    { id: "s9", nameEn: "Mastic", nameAr: "مستكة", price: "4.00" },
    { id: "s10", nameEn: "Grapes & Mint", nameAr: "عنب ونعنع", price: "4.00" },
    { id: "s11", nameEn: "Gum & Mint", nameAr: "علكة ونعنع", price: "4.00" },
    { id: "s12", nameEn: "Blueberry", nameAr: "بلوبيري", price: "4.00" },
    { id: "s13", nameEn: "Al Kayf", nameAr: "الكيف", price: "4.00" },
    { id: "s14", nameEn: "Orange & Mint", nameAr: "برتقال و نعنع", price: "4.00" },
    { id: "s15", nameEn: "Talet Al Qodus Shisha", nameAr: "ارجيلة طلة القدس", price: "8.00", isPopular: true },
    { id: "s16", nameEn: "Special Mix (Mazaya Tobacco)", nameAr: "ارجيلة سبيشل مكس", descEn: "Mazaya tobacco", descAr: "معسل مزايا", price: "4.00" },
    { id: "s17", nameEn: "Mango & Peach", nameAr: "مانجا و دراق", price: "4.00" },
    { id: "s18", nameEn: "Pomelo & Mint", nameAr: "بوملي و نعنع", price: "4.00" },
    { id: "s19", nameEn: "Love Shisha", nameAr: "ارجيلة لوڨ", price: "4.00" },
    { id: "s20", nameEn: "Arrow Gum", nameAr: "علكة سهم", price: "4.00" }
  ],
  addons: [
    { id: "a1", nameEn: "Pomegranate Molasses", nameAr: "دبس رمان", price: "0.50" },
    { id: "a2", nameEn: "Healthy Talet Al Qodus Salad", nameAr: "سلطة طلة القدس الصحية", price: "6.00" },
    { id: "a3", nameEn: "Pomelo Salad", nameAr: "سلطة بوملي", price: "6.00" },
    { id: "a4", nameEn: "Healthy Talet Al Qodus Meal", nameAr: "وجبة طلة القدس الصحية", descEn: "Even calories want a view!", descAr: "حتى الكالوريز بدها فيو", price: "5.75", isPopular: true },
    { id: "a5", nameEn: "Spicy Potato", nameAr: "بطاطا حارة", price: "3.00" }
  ]
};
